export * from "./Administracion"
export * from "./Contacto"
export * from "./Destacados"
export * from "./Home"
export * from "./EditarProducto"
export * from "./Favoritos"
export * from "./DescripcionProducto"