export * from "./Administracion"
export * from "./Busqueda"
export * from "./Contacto"
export * from "./Destacados"
export * from "./DetallesProducto"
export * from "./EditarProducto"
export * from "./Favoritos"
export * from "./Home"
